/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
#include QMK_KEYBOARD_H
#include "oled.c"
#include <stdbool.h>

#define BASE 0
#define _MEDIA 1
#define _NAV 2
#define _MOUSE 3
#define _SYM 4
#define _NUM 5
#define _FUN 6
#define _RGB 7
#define _SET2 8 //hangle_2 qwerty
#define _PUBG 9 //gaming

// Left-hand home row mods
#define HOME_A LGUI_T(KC_A)
#define HOME_R LCTL_T(KC_R)
#define HOME_S LALT_T(KC_S)
#define HOME_T LSFT_T(KC_T)

// Right-hand home row mods
#define HOME_N RSFT_T(KC_N)
#define HOME_E RALT_T(KC_E)
#define HOME_I RCTL_T(KC_I)
#define HOME_O RGUI_T(KC_O)
//
#define MEDIA_ESC LT(_MEDIA,KC_ESC)
#define NAV_SPC LT(_NAV,KC_SPC)
#define MOUSE_TAB LT(_MOUSE,KC_TAB)
#define SYM_ENT LT(_SYM,KC_ENT)
#define NUM_BSPC LT(_NUM,KC_BSPC)
#define FUN_DEL LT(_FUN,KC_DEL)

//Macro
enum custom_keycodes {
    TG_LNG,  //SET2로 전환 및 한영키 실행
};

bool is_set2_layer_active = false;

//key event record
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
		/* LAYER KEY */
		case TG_LNG:
			if(record->event.pressed){
				register_code(KC_LNG1);
				if (!is_set2_layer_active) {
                    // 레이어를 활성화하고 상태를 true로 변경
                    layer_on(_SET2);
                    is_set2_layer_active = true;
                } else { // 현재 레이어가 활성화되어 있다면
                    // 레이어를 비활성화하고 상태를 false로 변경
                    layer_off(_SET2);
                    is_set2_layer_active = false;
				}
            } else {
                // 키를 뗏을 때 - LT 레이어 비활성화
				unregister_code(KC_LNG1);
            }
        	break;
	}
	return true;
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	//COLEMAK DH
	[BASE] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
			KC_NO, KC_Q, KC_W, KC_F, KC_P, KC_B,											KC_J, KC_L, KC_U, KC_Y, KC_QUOT, KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO, HOME_A, HOME_R, HOME_S, HOME_T, KC_G, 									KC_M, HOME_N, HOME_E, HOME_I, HOME_O,  TG_LNG,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			MO(_RGB), KC_Z, KC_X, KC_C, KC_D, KC_V,											KC_K, KC_H, KC_COMM, KC_DOT, KC_SLSH, MO(_RGB),
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
											MEDIA_ESC, NAV_SPC, MOUSE_TAB,	SYM_ENT, NUM_BSPC, FUN_DEL
											//`--------------------------'  `--------------------------'
	),
	[_MEDIA] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_NO,	KC_MRWD, KC_VOLD, KC_VOLU, KC_MFFD,  KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_NO,   KC_NO,   KC_NO,      KC_MSTP, KC_MPLY, KC_MUTE
											//`--------------------------'  `--------------------------'
	),
	[_NAV] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_AGIN, KC_PSTE, KC_INS, KC_HOME, KC_PGUP,  KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_CAPS, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,                         KC_UNDO, KC_COPY, KC_CUT,  KC_END,  KC_PGDN, KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_NO,   KC_NO,   KC_NO,      KC_ENT,  KC_BSPC,  KC_DEL
											//`--------------------------'  `--------------------------'
	),
	[_MOUSE] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
		KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,                      KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,                      KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R,   KC_NO,   
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,    KC_NO,                      KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_U, KC_MS_R,	 KC_NO,    
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_NO,    KC_NO,  KC_NO,  	  KC_BTN1, KC_BTN2, KC_BTN3
											//`--------------------------'  `--------------------------'
	),
	[_SYM] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
		KC_NO,    KC_LCBR, KC_AMPR, KC_ASTR, KC_LPRN, KC_RCBR,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_COLN, KC_DLR,  KC_PERC, KC_CIRC, KC_PLUS,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_TILD, KC_EXLM, KC_DQUO, KC_HASH, KC_PIPE,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_LPRN, KC_RPRN, KC_UNDS,    KC_NO,   KC_NO,   KC_NO
											//`--------------------------'  `--------------------------'
	),
	[_NUM] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
		KC_NO,    KC_LBRC, KC_7,    KC_8,    KC_9,    KC_RBRC,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_SCLN, KC_4,    KC_5,    KC_6,    KC_EQL,                       KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_GRV,  KC_1,    KC_2,    KC_3,    KC_BSLS,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_DOT, KC_0, KC_MINS,    KC_NO,   KC_NO,   KC_NO
											//`--------------------------'  `--------------------------'
	),
	[_FUN] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
			KC_NO,    KC_F12,  KC_F7,   KC_F8,   KC_F9,   KC_PSCR,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,    KC_F11,  KC_F4,   KC_F5,   KC_F6,   KC_SCRL,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			KC_NO,    KC_F10,  KC_F1,   KC_F2,   KC_F3,   KC_PAUS,                      KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_MENU, KC_SPC,  KC_TAB,     KC_NO,   KC_NO,   KC_NO
										//`--------------------------'  `--------------------------'
	),
	[_RGB] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
			QK_BOOT,  KC_NO,   KC_NO,   KC_NO,   KC_NO,    KC_NO,                      KC_SLEP,   KC_PWR,   KC_NO,   KC_NO,   KC_NO,   QK_BOOT,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			RGB_TOG,  RGB_HUI, RGB_SAI, RGB_VAI, KC_NO,    KC_NO,                      BL_TOGG,   BL_UP,   KC_NO,   KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
			RGB_MOD,  RGB_HUD, RGB_SAD, RGB_VAD, KC_NO,    KC_NO,                      BL_BRTG,   BL_DOWN, BL_STEP, KC_NO,   KC_NO,   KC_NO,
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
												KC_NO,   KC_NO,   KC_NO,       KC_NO,   KC_NO,   KC_NO
											//`--------------------------'  `--------------------------'
	),
	//QWERTY_set2
	[_SET2] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
		KC_NO,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                         KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_NO,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                         KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, TG_LNG,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		MO(_RGB),    KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,                         KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, MO(_RGB),
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
											MEDIA_ESC, NAV_SPC, MOUSE_TAB,	SYM_ENT, NUM_BSPC, FUN_DEL
											//`--------------------------'  `--------------------------'
	),
	//Gaming
	[_PUBG] = LAYOUT_split_3x6_3(
		//,-----------------------------------------------------.                    ,-----------------------------------------------------.
		KC_TAB,    KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                         KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_NO,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_CAPS,    KC_A,    KC_S,    KC_D,    KC_F,    KC_G,                         KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, TG_LNG,
		//|--------+--------+--------+--------+--------+--------|                    |--------+--------+--------+--------+--------+--------|
		KC_LSFT,    KC_Z,    KC_X,    KC_LALT,    KC_V,    KC_B,                         KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, MO(_RGB),
		//|--------+--------+--------+--------+--------+--------+--------|  |--------+--------+--------+--------+--------+--------+--------|
											KC_C, KC_SPC, MOUSE_TAB,		SYM_ENT, NUM_BSPC, FUN_DEL
											//`--------------------------'  `--------------------------'
	),
};